from django.urls import path
from system import views

app_name = "system"

urlpatterns = [
    path("colaboradores/",views.gerenciar_colaboradores,name="gerenciar_colaboradores", ),
    path("clientes/",views.home_clientes,name="home_clientes",),
    path("clientes/cadastrar/",views.cadastrar_cliente_view,name="cadastrar_cliente",),
    path("clientes/listar/",views.listar_clientes_view,name="listar_clientes_view",),
    path("clientes/<int:pk>/visualizar/",views.visualizar_cliente,name="visualizar_cliente",),
    path("clientes/<int:pk>/editar/",views.editar_cliente_view,name="editar_cliente",),
    path("clientes/<int:pk>/excluir/",views.excluir_cliente,name="excluir_cliente",),
    path("clientes/dados/",views.api_dados_cliente,name="api_dados_cliente",),
    path("clientes/etapas-cadastro/",views.listar_etapas_cadastro,name="listar_etapas_cadastro",),
    path("clientes/etapas-cadastro/criar/",views.criar_etapa_cadastro,name="criar_etapa_cadastro",),
    path("clientes/etapas-cadastro/<int:pk>/editar/",views.editar_etapa_cadastro,name="editar_etapa_cadastro",),
    path("clientes/etapas-cadastro/<int:pk>/excluir/",views.excluir_etapa_cadastro,name="excluir_etapa_cadastro",),
    path("clientes/etapas-cadastro/<int:etapa_id>/campos/criar/",views.criar_campo_etapa,name="criar_campo_etapa",),
    path("clientes/etapas-cadastro/campos/<int:pk>/editar/",views.editar_campo_etapa,name="editar_campo_etapa",),
    path("clientes/etapas-cadastro/campos/<int:pk>/excluir/",views.excluir_campo_etapa,name="excluir_campo_etapa",),
    path("clientes/<int:pk>/dependentes/cadastrar/",views.cadastrar_dependente,name="cadastrar_dependente",),
    path("clientes/<int:pk>/dependentes/adicionar/",views.adicionar_dependente,name="adicionar_dependente",),
    path("clientes/<int:pk>/dependentes/<int:dependente_id>/remover/",views.remover_dependente,name="remover_dependente",),
    path("api/buscar-cep/",views.api_buscar_cep,name="api_buscar_cep",),
    path("partners/",views.home_partners,name="home_partners",),
    path("partners/criar/",views.criar_partner,name="criar_partner",),
    path("partners/listar/",views.listar_partners,name="listar_partners",),
    path("partners/<int:pk>/visualizar/",views.visualizar_partner,name="visualizar_partner",),
    path("partners/<int:pk>/editar/",views.editar_partner,name="editar_partner",),
    path("partners/<int:pk>/excluir/",views.excluir_partner,name="excluir_partner",),
    path("viagens/",views.home_viagens,name="home_viagens",),
    path("viagens/criar/",views.criar_viagem,name="criar_viagem",),
    path("viagens/listar/",views.listar_viagens,name="listar_viagens",),
    path("viagens/<int:pk>/visualizar/",views.visualizar_viagem,name="visualizar_viagem",),
    path("viagens/<int:pk>/editar/",views.editar_viagem,name="editar_viagem",),
    path("viagens/<int:pk>/excluir/",views.excluir_viagem,name="excluir_viagem",),
    path("viagens/<int:viagem_id>/formularios/",views.listar_formularios_viagem,name="listar_formularios_viagem",),
    path("viagens/<int:viagem_id>/formularios/<int:cliente_id>/visualizar/",views.visualizar_formulario_cliente,name="visualizar_formulario_cliente",),
    path("viagens/<int:viagem_id>/formularios/<int:cliente_id>/editar/",views.editar_formulario_cliente,name="editar_formulario_cliente",),
    path("viagens/<int:viagem_id>/formularios/<int:cliente_id>/excluir/",views.excluir_respostas_formulario,name="excluir_respostas_formulario",),
    path("paises-destino/",views.home_paises_destino,name="home_paises_destino",),
    path("paises-destino/criar/",views.criar_pais_destino,name="criar_pais_destino",),
    path("paises-destino/listar/",views.listar_paises_destino,name="listar_paises_destino",),
    path("paises-destino/<int:pk>/visualizar/",views.visualizar_pais_destino,name="visualizar_pais_destino",),
    path("paises-destino/<int:pk>/editar/",views.editar_pais_destino,name="editar_pais_destino",),
    path("paises-destino/<int:pk>/verificar-exclusao/",views.verificar_exclusao_pais_destino,name="verificar_exclusao_pais_destino",),
    path("paises-destino/<int:pk>/excluir/",views.excluir_pais_destino,name="excluir_pais_destino",),
    path("tipos-visto/",views.home_tipos_visto,name="home_tipos_visto",),
    path("tipos-visto/criar/",views.criar_tipo_visto,name="criar_tipo_visto",),
    path("tipos-visto/listar/",views.listar_tipos_visto,name="listar_tipos_visto",),
    path("tipos-visto/<int:pk>/visualizar/",views.visualizar_tipo_visto,name="visualizar_tipo_visto",),
    path("tipos-visto/<int:pk>/editar/",views.editar_tipo_visto,name="editar_tipo_visto",),
    path("tipos-visto/<int:pk>/excluir/",views.excluir_tipo_visto,name="excluir_tipo_visto",),
    path("api/tipos-visto/",views.api_tipos_visto,name="api_tipos_visto",),
    path("formularios/",views.home_formularios,name="home_formularios",),
    path("formularios/criar/",views.selecionar_viagem_cliente_formulario,name="selecionar_viagem_cliente_formulario",),
    path("formularios/listar/",views.listar_formularios,name="listar_formularios",),
    path("formularios/tipos/",views.home_tipos_formulario,name="home_tipos_formulario",),
    path("formularios/tipos/criar/",views.criar_formulario,name="criar_formulario",),
    path("formularios/tipos/listar/",views.listar_tipos_formulario,name="listar_tipos_formulario",),
    path("formularios/tipos/<int:pk>/editar/",views.editar_formulario,name="editar_formulario",),
    path("formularios/tipos/<int:pk>/excluir/",views.excluir_formulario,name="excluir_formulario",),
    path("formularios/tipos/<int:formulario_id>/perguntas/criar/",views.criar_pergunta,name="criar_pergunta",),
    path("processos/",views.home_processos,name="home_processos",),
    path("processos/criar/",views.criar_processo,name="criar_processo",),
    path("processos/listar/",views.listar_processos,name="listar_processos",),
    path("processos/<int:pk>/visualizar/",views.visualizar_processo,name="visualizar_processo",),
    path("processos/<int:pk>/editar/",views.editar_processo,name="editar_processo",),
    path("processos/<int:pk>/excluir/",views.excluir_processo,name="excluir_processo",),
    path("processos/<int:processo_pk>/etapas/<int:etapa_pk>/remover/",views.remover_etapa_processo,name="remover_etapa_processo",),
    path("processos/<int:processo_pk>/etapas/adicionar/<int:status_pk>/",views.adicionar_etapa_processo,name="adicionar_etapa_processo",),
    path("processos/status/",views.listar_status_processo,name="listar_status_processo",),
    path("processos/status/criar/",views.criar_status_processo,name="criar_status_processo",),
    path("processos/status/<int:pk>/editar/",views.editar_status_processo,name="editar_status_processo",),
    path("processos/status/<int:pk>/excluir/",views.excluir_status_processo,name="excluir_status_processo",),
    path("api/prazo-status-processo/",views.api_prazo_status_processo,name="api_prazo_status_processo",),
    path("api/clientes-viagem/",views.api_clientes_viagem,name="api_clientes_viagem",),
    path("api/status-processo/",views.api_status_processo,name="api_status_processo",),
    # Financeiro
    path("financeiro/",views.home_financeiro,name="home_financeiro",),
    path("financeiro/listar/",views.listar_financeiro,name="listar_financeiro",),
    path("financeiro/<int:pk>/dar-baixa/",views.dar_baixa_financeiro,name="dar_baixa_financeiro",),
    # Administração
    path("administracao/",views.home_administracao,name="home_administracao",),
    # Usuários
    path("administracao/usuarios/",views.listar_usuarios,name="listar_usuarios",),
    path("administracao/usuarios/criar/",views.criar_usuario,name="criar_usuario",),
    path("administracao/usuarios/<int:pk>/editar/",views.editar_usuario,name="editar_usuario",),
    path("administracao/usuarios/<int:pk>/excluir/",views.excluir_usuario,name="excluir_usuario",),
    # Perfis/Permissões
    path("administracao/perfis/",views.listar_perfis,name="listar_perfis",),
    path("administracao/perfis/criar/",views.criar_perfil,name="criar_perfil",),
    path("administracao/perfis/<int:pk>/editar/",views.editar_perfil,name="editar_perfil",),
    path("administracao/perfis/<int:pk>/excluir/",views.excluir_perfil,name="excluir_perfil",),
    # Módulos
    path("administracao/modulos/",views.listar_modulos,name="listar_modulos",),
    path("administracao/modulos/criar/",views.criar_modulo,name="criar_modulo",),
    path("administracao/modulos/<int:pk>/editar/",views.editar_modulo,name="editar_modulo",),
    path("administracao/modulos/<int:pk>/excluir/",views.excluir_modulo,name="excluir_modulo",),
    # APIs auxiliares
    path("api/cliente-info/", views.api_cliente_info, name="api_cliente_info"),
    path("perguntas/<int:pk>/editar/",views.editar_pergunta,name="editar_pergunta",),
    path("perguntas/<int:pk>/excluir/",views.excluir_pergunta,name="excluir_pergunta",),
    path("perguntas/<int:pergunta_id>/opcoes/criar/",views.criar_opcao_selecao,name="criar_opcao_selecao",),
    path("opcoes/<int:pk>/editar/",views.editar_opcao_selecao,name="editar_opcao_selecao",),
    path("opcoes/<int:pk>/excluir/",views.excluir_opcao_selecao,name="excluir_opcao_selecao",),
    # Área do Cliente
    path("cliente/logout/",views.cliente_logout_view,name="cliente_logout",),
    path("cliente/dashboard/",views.cliente_dashboard,name="cliente_dashboard",),
    path("cliente/viagem/<int:viagem_id>/formulario/",views.cliente_visualizar_formulario,name="cliente_visualizar_formulario",),
    path("cliente/viagem/<int:viagem_id>/salvar-resposta/",views.cliente_salvar_resposta,name="cliente_salvar_resposta",),
]

