from django.urls import path
from system import views

app_name = "system"

urlpatterns = [
    path("clientes/",views.home_clients,name="home_clients",),
    path("clientes/cadastrar/",views.register_client_view,name="register_client",),
    path("clientes/listar/",views.list_clients_view,name="list_clients_view",),
    path("clientes/<int:pk>/visualizar/",views.view_client,name="view_client",),
    path("clientes/<int:pk>/editar/",views.edit_client_view,name="edit_client",),
    path("clientes/<int:pk>/excluir/",views.delete_client,name="delete_client",),
    path("clientes/dados/",views.api_client_data,name="api_client_data",),
    path("clientes/etapas-cadastro/",views.list_registration_steps,name="list_registration_steps",),
    path("clientes/etapas-cadastro/criar/",views.create_registration_step,name="create_registration_step",),
    path("clientes/etapas-cadastro/<int:pk>/editar/",views.edit_registration_step,name="edit_registration_step",),
    path("clientes/etapas-cadastro/<int:pk>/excluir/",views.delete_registration_step,name="delete_registration_step",),
    path("clientes/etapas-cadastro/<int:step_id>/campos/criar/",views.create_step_field,name="create_step_field",),
    path("clientes/etapas-cadastro/campos/<int:pk>/editar/",views.edit_step_field,name="edit_step_field",),
    path("clientes/etapas-cadastro/campos/<int:pk>/excluir/",views.delete_step_field,name="delete_step_field",),
    path("clientes/<int:client_id>/lembretes/criar/",views.create_reminder,name="create_reminder",),
    path("lembretes/<int:pk>/toggle/",views.toggle_reminder,name="toggle_reminder",),
    path("lembretes/<int:pk>/excluir/",views.delete_reminder,name="delete_reminder",),
    path("clientes/<int:pk>/dependentes/cadastrar/",views.register_dependent,name="register_dependent",),
    path("clientes/<int:pk>/dependentes/adicionar/",views.add_dependent,name="add_dependent",),
    path("clientes/<int:pk>/dependentes/<int:dependent_id>/remover/",views.remove_dependent,name="remove_dependent",),
    path("api/buscar-cep/",views.api_search_zip,name="api_search_zip",),
    path("api/extrair-passaporte/",views.api_extract_passport,name="api_extract_passport",),
    path("partners/",views.home_partners,name="home_partners",),
    path("partners/criar/",views.create_partner,name="create_partner",),
    path("partners/listar/",views.list_partners,name="list_partners",),
    path("partners/<int:pk>/visualizar/",views.view_partner,name="view_partner",),
    path("partners/<int:pk>/editar/",views.edit_partner,name="edit_partner",),
    path("partners/<int:pk>/excluir/",views.delete_partner,name="delete_partner",),
    path("viagens/",views.home_trips,name="home_trips",),
    path("viagens/criar/",views.create_trip,name="create_trip",),
    path("viagens/listar/",views.list_trips,name="list_trips",),
    path("viagens/<int:pk>/visualizar/",views.view_trip,name="view_trip",),
    path("viagens/<int:pk>/editar/",views.edit_trip,name="edit_trip",),
    path("viagens/<int:pk>/excluir/",views.delete_trip,name="delete_trip",),
    path("viagens/<int:pk>/trocar-principal/<int:client_id>/",views.switch_trip_principal,name="switch_trip_principal",),
    path("viagens/<int:trip_id>/formularios/",views.list_trip_forms,name="list_trip_forms",),
    path("viagens/<int:trip_id>/formularios/<int:client_id>/visualizar/",views.view_client_form,name="view_client_form",),
    path("viagens/<int:trip_id>/formularios/<int:client_id>/editar/",views.edit_client_form,name="edit_client_form",),
    path("viagens/<int:trip_id>/formularios/<int:client_id>/excluir/",views.delete_form_answers,name="delete_form_answers",),
    path("paises-destino/",views.home_destination_countries,name="home_destination_countries",),
    path("paises-destino/criar/",views.create_destination_country,name="create_destination_country",),
    path("paises-destino/listar/",views.list_destination_countries,name="list_destination_countries",),
    path("paises-destino/<int:pk>/visualizar/",views.view_destination_country,name="view_destination_country",),
    path("paises-destino/<int:pk>/editar/",views.edit_destination_country,name="edit_destination_country",),
    path("paises-destino/<int:pk>/verificar-exclusao/",views.verify_destination_country_deletion,name="verify_destination_country_deletion",),
    path("paises-destino/<int:pk>/excluir/",views.delete_destination_country,name="delete_destination_country",),
    path("tipos-visto/",views.home_visa_types,name="home_visa_types",),
    path("tipos-visto/criar/",views.create_visa_type,name="create_visa_type",),
    path("tipos-visto/listar/",views.list_visa_types,name="list_visa_types",),
    path("tipos-visto/<int:pk>/visualizar/",views.view_visa_type,name="view_visa_type",),
    path("tipos-visto/<int:pk>/editar/",views.edit_visa_type,name="edit_visa_type",),
    path("tipos-visto/<int:pk>/excluir/",views.delete_visa_type,name="delete_visa_type",),
    path("api/tipos-visto/",views.api_visa_types,name="api_visa_types",),
    path("formularios/",views.home_forms,name="home_forms",),
    path("formularios/criar/",views.select_trip_client_form,name="select_trip_client_form",),
    path("formularios/listar/",views.list_forms,name="list_forms",),
    path("formularios/tipos/",views.home_form_types,name="home_form_types",),
    path("formularios/tipos/criar/",views.create_form,name="create_form",),
    path("formularios/tipos/listar/",views.list_form_types,name="list_form_types",),
    path("formularios/tipos/<int:pk>/editar/",views.edit_form,name="edit_form",),
    path("formularios/tipos/<int:pk>/excluir/",views.delete_form,name="delete_form",),
    path("formularios/tipos/<int:form_id>/etapas/criar/",views.create_form_stage,name="create_form_stage",),
    path("formularios/etapas/<int:pk>/editar/",views.edit_form_stage,name="edit_form_stage",),
    path("formularios/etapas/<int:pk>/excluir/",views.delete_form_stage,name="delete_form_stage",),
    path("formularios/tipos/<int:form_id>/perguntas/criar/",views.create_question,name="create_question",),
    path("processos/",views.home_processes,name="home_processes",),
    path("processos/criar/",views.create_process,name="create_process",),
    path("processos/listar/",views.list_processes,name="list_processes",),
    path("processos/<int:pk>/visualizar/",views.view_process,name="view_process",),
    path("processos/<int:pk>/editar/",views.edit_process,name="edit_process",),
    path("processos/<int:pk>/excluir/",views.delete_process,name="delete_process",),
    path("processos/<int:process_pk>/etapas/<int:stage_pk>/remover/",views.remove_process_stage,name="remove_process_stage",),
    path("processos/<int:process_pk>/etapas/adicionar/<int:status_pk>/",views.add_process_stage,name="add_process_stage",),
    path("processos/status/",views.list_process_status,name="list_process_status",),
    path("processos/status/criar/",views.create_process_status,name="create_process_status",),
    path("processos/status/<int:pk>/editar/",views.edit_process_status,name="edit_process_status",),
    path("processos/status/<int:pk>/excluir/",views.delete_process_status,name="delete_process_status",),
    path("api/prazo-status-processo/",views.api_process_status_deadline,name="api_process_status_deadline",),
    path("api/clientes-viagem/",views.api_trip_clients,name="api_trip_clients",),
    path("api/status-processo/",views.api_process_status,name="api_process_status",),
    path("api/dependentes-cliente/",views.api_client_dependents,name="api_client_dependents",),
    path("api/viagens-cliente/",views.api_client_trips,name="api_client_trips",),
                
    path("financeiro/",views.home_financial,name="home_financial",),
    path("financeiro/listar/",views.list_financial,name="list_financial",),
    path("financeiro/<int:pk>/dar-baixa/",views.settle_financial,name="settle_financial",),
                   
    path("administracao/",views.home_admin,name="home_admin",),
              
    path("administracao/usuarios/",views.list_users,name="list_users",),
    path("administracao/usuarios/criar/",views.create_user,name="create_user",),
    path("administracao/usuarios/<int:pk>/editar/",views.edit_user,name="edit_user",),
    path("administracao/usuarios/<int:pk>/excluir/",views.delete_user,name="delete_user",),
                       
    path("administracao/perfis/",views.list_profiles,name="list_profiles",),
    path("administracao/perfis/criar/",views.create_profile,name="create_profile",),
    path("administracao/perfis/<int:pk>/editar/",views.edit_profile,name="edit_profile",),
    path("administracao/perfis/<int:pk>/excluir/",views.delete_profile,name="delete_profile",),
             
    path("administracao/modulos/",views.list_modules,name="list_modules",),
    path("administracao/modulos/criar/",views.create_module,name="create_module",),
    path("administracao/modulos/<int:pk>/editar/",views.edit_module,name="edit_module",),
    path("administracao/modulos/<int:pk>/excluir/",views.delete_module,name="delete_module",),
                     
    path("api/cliente-info/", views.api_client_info, name="api_client_info"),
    path("perguntas/<int:pk>/editar/",views.edit_question,name="edit_question",),
    path("perguntas/<int:pk>/excluir/",views.delete_question,name="delete_question",),
    path("perguntas/<int:question_id>/opcoes/criar/",views.create_select_option,name="create_select_option",),
    path("opcoes/<int:pk>/editar/",views.edit_select_option,name="edit_select_option",),
    path("opcoes/<int:pk>/excluir/",views.delete_select_option,name="delete_select_option",),
                     
    path("cliente/logout/",views.client_logout_view,name="client_logout",),
    path("cliente/dashboard/",views.client_dashboard,name="client_dashboard",),
    path("cliente/viagem/<int:trip_id>/formulario/",views.client_view_form,name="client_view_form",),
    path("cliente/viagem/<int:trip_id>/salvar-resposta/",views.client_save_answer,name="client_save_answer",),
    path("parceiro/dashboard/",views.partner_dashboard,name="partner_dashboard",),
    path("parceiro/clientes/<int:client_id>/visualizar/",views.partner_view_client,name="partner_view_client",),
    path("parceiro/logout/",views.partner_logout_view,name="partner_logout",),
]

